version: '3.7'

services:
    mysql:
      container_name: econcilia_prod
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=econcilia
      security_opt:
        - seccomp:unconfined
      ports:
        - 3306:3306
      networks:
        - econcilia_network

    mysql_test:
      container_name: econcilia_test
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=econcilia_test
      security_opt:
        - seccomp:unconfined
      ports:
        - 3307:3306
      networks:
        - econcilia_network

networks:
  econcilia_network: